apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense3
  region: us-east-1

managedNodeGroups:
  - name: expense3
    instanceType: m5.large
    desiredCapacity: 3
    spot: true